### ISSUE TITLE
A bug in the training phase

### ISSUE THREAD

**Issue by CHENBIN99** [Galaxies99/NHDRRNet-pytorch#3]
Hello，first thanks for your code!

when I train the model follow you tips, I found that the code will go wrong when I was training. Then I found the error occurs in `models/NHDRRNet.py`, line 206. In more detail, the error will occur when runing the function of `eval_one_epoch()` after finishing one epoch. 

The error info is **RuntimeError: Sizes of tensors must match except in dimension 2. Got 125 and 124 (The offending index is 0)**, I find that the reason why the error occur is the size of the model input is  unsuitable, so when they cat each other after decoder, the size will be unequal. 

My solution is **change 8 to 16** in `utils/dataprocessor.py`, line 99 & line 100. After that, the size can be equal after a serier of decoder.

My solution may not be the best, so I wish you to fix this bug, Thanks~

**Comment by Galaxies99** [comment]
Hello!

Thank you for reporting the bugs, and your solution is absolutely correct! The training scripts is adapted from another HDR model which has less encoders & decoders (8 is correct for that model). It is possible that we upload the wrong file previously (don't worry about the other files, after examining the files today, I'm sure that they are in the correct version).

The bug is fixed in the latest commits. Thank you again for your kindly notifications!
